### ISSUE TITLE
Doesn't work for scoped packages

### ISSUE THREAD

**Issue by smiller171** [arve0/npm-download-size#2]
If I try to check on a scoped package (`@nuxtjs/vuetify`) the package is incorrectly reported as not existing.

**Comment by arve0** [comment]
Thanks for reporting. Away for about a week, will check when I’m back.

fre. 23. mar. 2018 kl. 20:31 skrev Scott Miller <notifications@github.com>:

**Comment by smiller171** [comment]
Turns out you need to replace the `/` with `%2F`

**Comment by smiller171** [comment]
@arve0 did you take a look at this PR?

**Comment by arve0** [comment]
I’m still on vacation and have no computer with me.

søn. 1. apr. 2018 kl. 05:50 skrev Scott Miller <notifications@github.com>:

**Comment by arve0** [comment]
Was related to issue https://github.com/npm/registry/issues/34. Fix is on the way.
