### ISSUE TITLE
Cannot find valid npm package

### ISSUE THREAD

**Issue by heri16** [arve0/npm-download-size#5]
When trying to analyze `realm` package, the tool returns an invalid error.
https://www.npmjs.com/package/realm

**Comment by arve0** [comment]
Thanks for reporting. NPM registry seems to no longer allow cross origin requests to https://registry.npmjs.com/-/v1/search (or have an outage right now).

https://arve0.github.io/npm-download-size/#realm works as expected.

**Comment by arve0** [comment]
Reported in https://github.com/npm/registry/issues/332

**Comment by arve0** [comment]
Registry search is back up again.
