### ISSUE TITLE
Doesn't seem to work with scoped packages

### ISSUE THREAD

**Issue by XhmikosR** [arve0/npm-download-size#50]
Hey, @arve0, thanks for making this tool!

I've noticed that it doesn't work with scoped packages, i.e. `@xhmikosr/bin-wrapper`.

Is there any chance this could be fixed?

Thanks!

**Comment by arve0** [comment]
Works for @microsoft. Is the package public?

**Comment by XhmikosR** [comment]
Yup. Everything is public.

**Comment by arve0** [comment]
Probably a bug then. Thanks for reporting.

**Comment by arve0** [comment]
It's the suggestion API that does not have the package:

```
$ curl 'https://api.npms.io/v2/search/suggestions?q=@xhmikosr/bin-wrapper'
[]
```

Works with cli:
```
$ download-size @xhmikosr/bin-wrapper
@xhmikosr/bin-wrapper@9.0.0: 1.31 MiB
```

And bundlephobia: https://bundlephobia.com/package/@xhmikosr/bin-wrapper@9.0.0

Closing, as I do not control api.npms.io.
